### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by Dina-H-Alhamed** [SMorettini/CNNs-on-CHB-MIT#14] opened 2023-01-25 06:13 UTC
![image](https://user-images.githubusercontent.com/113273339/214493372-ec47d221-6e30-4c40-b564-5ff20cde49c5.png)

I got this error even i put a path in the txt file

**Comment by SMorettini** [comment] 2023-01-27 07:10
It seems that `OutputPathModels` is containing the wrong path. Can you print it in line 214 of CNN.py to see its content?

**Comment by Femotop** [comment] 2023-03-09 13:12
I have the same problem 
should I put the path of the dataset in the (OutputPathModels)??

**Comment by SMorettini** [comment] 2023-03-10 07:02
Hello, did you read the README at https://github.com/SMorettini/CNNs-on-CHB-MIT/blob/62d68f99c997d751117563bcce2f1728847bf1ef/README.md?plain=1#LL38C40-L38C40 ?

**Comment by HireTheHero** [comment] 2023-05-17 15:41
The cause of this issue in my case is ordering of the lines below in [CNN.py](https://github.com/SMorettini/CNNs-on-CHB-MIT/blob/master/CNN.py);
```
    if not os.path.exists(OutputPathModels):
        os.makedirs(OutputPathModels)
    loadParametersFromFile("PARAMETERS_CNN.txt")
```

Since initial value for `OutputPathModels` is "", executing `os.makedirs(OutputPathModels)` before calling `loadParametersFromFile` would most likely result in NotFound error.

If it's ok for you, I can make a small PR for this.

**Comment by SMorettini** [comment] 2023-05-19 06:30
Thank you for the pull request. I just accepted it and merged it. So I close this issue.

**Closed as completed by SMorettini** 2023-05-19 06:30 UTC
